// Code generated by mockery v1.0.0. DO NOT EDIT.

package vulnsrc

import (
	db "github.com/aquasecurity/trivy-db/pkg/db"
	mock "github.com/stretchr/testify/mock"
)

// MockOperation is an autogenerated mock type for the Operation type
type MockOperation struct {
	mock.Mock
}

// SetMetadata provides a mock function with given fields: metadata
func (_m *MockOperation) SetMetadata(metadata db.Metadata) error {
	ret := _m.Called(metadata)

	var r0 error
	if rf, ok := ret.Get(0).(func(db.Metadata) error); ok {
		r0 = rf(metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
