// Code generated by mockery v1.0.0. DO NOT EDIT.

package vulnsrc

import mock "github.com/stretchr/testify/mock"

// MockVulnSrc is an autogenerated mock type for the VulnSrc type
type MockVulnSrc struct {
	mock.Mock
}

// Update provides a mock function with given fields: dir
func (_m *MockVulnSrc) Update(dir string) error {
	ret := _m.Called(dir)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(dir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
