// Code generated by mockery v1.0.0. DO NOT EDIT.

package github

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockVCSClientInterface is an autogenerated mock type for the VCSClientInterface type
type MockVCSClientInterface struct {
	mock.Mock
}

// UploadReleaseAssets provides a mock function with given fields: ctx, filePaths
func (_m *MockVCSClientInterface) UploadReleaseAssets(ctx context.Context, filePaths []string) error {
	ret := _m.Called(ctx, filePaths)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, filePaths)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
